### PR TITLE
Update missing changes to match the latest

### PR DESCRIPTION
**Pull request by deepakala-k**
latest ecmd, powervm-handler package details are added

Signed-off-by: deepakala <deepakala.karthikeyan@ibm.com>

### CODE REVIEW

**Comment by ojayanth** [comment]
Changes looks good. 
 Build used for development is  based on https://github.ibm.com/openbmc/openbmc/tree/1050-ghe branch. Not sure @rfrandse syncs this from 1050-ghe branch.

@anoo1 what is the process followed to get these changes in upstream? this will help to avoid next time master rebase issues?

**Comment by geissonator** [comment]
These are all meta-openpower changes so should be easy to get into upstream. Please submit to gerrit.

Also, openbmc/openbmc PR's should go against 1050-ghe so we get better CI. Reed will synch those up to ibm-openbmc periodically.

**Comment by deepakala-k** [comment]
Raised the review against 1050-ghe

**Comment by devenrao** [comment]
> 

powervm-handler is not in open-power rather downstream [ibm-openbmc](https://github.com/ibm-openbmc/powervm-handler), cannot push the changes to gerrit

**Pull request closed without merging**
