### PR TITLE
phosphor-time-manager: srcrev bump 295b96b743..261525d177

### PR DESCRIPTION
**Pull request by lxwinspur**
Update phosphor-time-manager_git.bb file

Signed-off-by: George Liu <liuxiwei@inspur.com>

### CODE REVIEW

**Comment by geissonator** [comment]
jenkins run tests please

**Comment by geissonator** [comment]
@lxwinspur  could you provide some info on why this PR is needed?

**Comment by lxwinspur** [comment]
> @lxwinspur could you provide some info on why this PR is needed?

Hi, @geissonator 
please check this issue:
https://github.com/ibm-openbmc/dev/issues/3588

**Comment by geissonator** [comment]
List of changes here:
```
phosphor-time-manager $git shortlog 295b96b743cded8cdba7b0cda59dc1cfe84f64f0..261525d177ffd7f098c5040c732a7c5f612eddbd
Brad Bishop (1):
      systemd: use qualified path

George Liu (5):
      Remove is_method_error method
      logging: switch to lg2
      meson: update dependency
      Update clang-format
      Fix cppcheck warnings

Manojkiran Eda (1):
      Add OWNERS file

Patrick Williams (2):
      build: switch to C++20
      build: remove explicit C++ standard check
```

Sounds like this is mostly just additional FFDC so should we target 1040?

**Comment by geissonator** [comment]
Please move this to IPS branch if it's needed.

**Pull request closed without merging**
