### PR TITLE
OP940: bmcweb: Don't require X-XSRF-TOKEN

### PR DESCRIPTION
**Pull request by spinler**
By default, bmcweb requires the X-XSRF-TOKEN value that is obtained from
a login to be passed in to everything but a GET request.

However, op940 has users (xcat) that require the op930 behavior that
didn't require that, even though this is less secure.

Tested:
Do a DeleteAll with the cookie jar file only:
$ curl -b cjar -k -H 'Content-Type: application/json' -X POST -d '{"data":[]}' https://$IP/xyz/openbmc_project/logging/action/DeleteAll
{
  "data": null,
  "message": "200 OK",
  "status": "ok"
}

Signed-off-by: Matt Spinler <spinler@us.ibm.com>

### CODE REVIEW

**Comment by geissonator** [comment]
Sound like Gunnar is still doing some testing around this.

**Comment by gtmills** [comment]
Are we sure this is worth it?

**Comment by geissonator** [comment]
> Are we sure this is worth it?

We've decided its required we be backward compatible with xcat (and anyone else using our existing REST interfaces). Is there another solution?

**Comment by gtmills** [comment]
> We've decided its required we be backward compatible with xcat (and anyone else using our existing REST interfaces). Is there another solution?

Don't disable this and thus don't be backward compatible.

**Pull request merged**
