### PR TITLE
meta-openpower: Added the recipe for HardwareIsolation feature

### PR DESCRIPTION
**Pull request by RameshIyyar**

### CODE REVIEW

**Comment by geissonator** [comment]
add to approvelist

**Comment by geissonator** [comment]
Our general approach with ibm-openbmc/openbmc changes is to do PR's in our downstream GHE so we get the full CI process then Reed will push out to this location. Please be sure to point to upstream gerrit commit in PR's.

**Comment by RameshIyyar** [comment]
> Our general approach with ibm-openbmc/openbmc changes is to do PR's in our downstream GHE so we get the full CI process then Reed will push out to this location. Please be sure to point to upstream gerrit commit in PR's.

The openpower-hw-isolation repository is sitting _only_ in https://github.com/ibm-openbmc/openpower-hw-isolation so, I think we cannot add Gerrit patch for the same but, Yes I will push new PR to downstream GHE for the same once this is merged.

**Comment by RameshIyyar** [comment]
CI is failed due to the version bump (initial version) which does not contain the meson build file. I will bump once the following PR is merged https://github.com/ibm-openbmc/openpower-hw-isolation/pull/2. This PR is just created for recipe review.

**Comment by rfrandse** [comment]
This PR's commit moved to GHE.

**Comment by RameshIyyar** [comment]
@rfrandse  What is the process we are following to sync the GHE/openbmc and ibm-openbmc/openbmc

**Pull request closed without merging**
