### PR TITLE
1030.ips: Remove the AssetTag persistence

### PR DESCRIPTION
**Pull request by lxwinspur**
The AssetTag persistence function will cause the probabilistic startup failure of the IPS localized BMC, which is temporarily removed in the current version.

### CODE REVIEW

**Comment by lxwinspur** [comment]
@RameshIyyar 
Please review it, thanks.

**Comment by RameshIyyar** [comment]
> @RameshIyyar Please review it, thanks.

Hi George, 

Sorry, I am not much familiar with the bmcweb component so I would suggest you tag the component maintainer for the review.

**Comment by lxwinspur** [comment]
Sure, Thanks @RameshIyyar 
Actually, This is a function customized by the ips branch, @anoo1 @geissonator  could you please review it? thanks :)

**Comment by lxwinspur** [comment]
@mzipse 
FYI

**Review by geissonator — APPROVED** [review]
Seems fine to me, just a revert of the AssetTag persistence which was IPS specific

**Pull request merged**
